#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
CVAT UI 汉化脚本 v2 —— 直接替换模式（非 i18n）
对 cvat-ui/src 下所有 .tsx / .ts 文件中的 UI 可见文本进行中文替换。
支持四种匹配模式：
  1. 双引号字符串  "Some Text"
  2. 单引号字符串  'Some Text'
  3. JSX 同行文本节点  > Some Text <
  4. JSX 独占行文本节点（缩进后跟换行）
"""

import os
import re
import sys
from pathlib import Path

# ============================================================
# 翻译词典（长字符串优先，避免短词提前命中）
# ============================================================
TRANSLATIONS: list[tuple[str, str]] = [
    # ─── 长句/完整句子（必须排在前面） ────────────────────────
    ("Specify source storage for import resources like annotation, backups",
     "指定用于导入标注、备份等资源的源存储"),
    ("Specify target storage for export resources like annotation, backups",
     "指定用于导出标注、备份等资源的目标存储"),
    ("Repeat the latest procedure of drawing with the same parameters",
     "使用相同参数重复最近的绘制操作"),
    ("To get started with your annotation project", "开始您的标注项目"),
    ("It will save annotations and set the job state to", "将保存标注并将作业状态设置为"),
    ("Would you like to finish the job?", "确定要完成该作业吗？"),
    ("Would you like to update current job state?", "确定要更新当前作业状态吗？"),
    ("Job state will be switched to", "作业状态将切换为"),
    ("You tagged the job as completed", "您已将作业标记为已完成"),
    ("Are you sure you want to remove the task?", "确定要删除该任务吗？"),
    ("Are you sure you want to delete the project?", "确定要删除该项目吗？"),
    ("Are you sure you want to delete the job?", "确定要删除该作业吗？"),
    ("Are you sure you want to remove", "确定要删除"),
    ("Are you sure you want to delete", "确定要删除"),
    ("The task and related data will be deleted", "任务及相关数据将被删除"),
    ("The project and related data will be deleted", "项目及相关数据将被删除"),
    ("All task data will be lost", "所有任务数据将丢失"),
    ("All project data will be lost", "所有项目数据将丢失"),
    ("This action cannot be undone", "此操作不可撤销"),
    ("Open/hide the list of available shortcuts", "打开/关闭快捷键列表"),
    ("Open/hide settings dialog", "打开/关闭设置对话框"),
    ("Two passwords that you enter is inconsistent!", "两次输入的密码不一致！"),
    ("Please, specify frame selection method", "请指定帧选择方法"),
    ("Please, specify a name", "请指定名称"),
    ("Please specify an email address", "请输入邮箱地址"),
    ("Please input your password!", "请输入您的密码！"),
    ("Please input new password!", "请输入新密码！"),
    ("Please confirm your new password!", "请确认新密码！"),
    ("Please specify a password", "请输入密码"),
    ("Please input your username or email", "请输入用户名或邮箱"),
    ("Please input your email", "请输入邮箱"),
    ("Please input your password", "请输入密码"),
    ("Please input your username", "请输入用户名"),
    ("Please input a correct email address", "请输入正确的邮箱地址"),
    ("Please confirm your password", "请确认密码"),
    ("Please confirm your new password", "请确认新密码"),
    ("You must accept to continue!", "您必须接受才能继续！"),
    ("Passwords must match", "两次密码不一致"),
    ("At least 8 characters required", "至少需要8个字符"),
    ("Could not save consensus settings", "无法保存共识设置"),
    ("Could not open the page", "无法打开该页面"),
    ("Settings have been updated", "设置已更新"),
    ("Token is invalid or has expired", "令牌无效或已过期"),
    ("Account created successfully", "账号创建成功"),
    ("Activation link has been sent", "激活链接已发送"),
    ("Please check your email", "请检查您的邮箱"),
    ("Your email has been confirmed", "邮箱已确认"),
    ("Password reset link sent", "密码重置链接已发送"),
    ("Password changed successfully", "密码修改成功"),
    ("Copied to clipboard", "已复制到剪贴板"),
    ("Task has been created", "任务已创建"),
    ("Task has been updated", "任务已更新"),
    ("Task has been deleted", "任务已删除"),
    ("Project has been created", "项目已创建"),
    ("Project has been updated", "项目已更新"),
    ("Project has been deleted", "项目已删除"),
    ("Job has been updated", "作业已更新"),
    ("Changes have been saved", "更改已保存"),
    ("Changes saved", "更改已保存"),
    ("Annotation has been saved", "标注已保存"),
    ("Settings have been saved", "设置已保存"),
    ("Job state updated", "作业状态已更新"),
    ("Something went wrong", "出现错误"),
    ("Connection error", "连接错误"),
    ("Network error", "网络错误"),
    ("Access denied", "访问被拒绝"),
    ("Not authorized", "未授权"),
    ("Session expired", "会话已过期"),
    ("Internal server error", "内部服务器错误"),
    ("Server error", "服务器错误"),
    ("Server unavailable", "服务器不可用"),
    ("The server is not available", "服务器不可用"),
    ("Please try again later", "请稍后重试"),
    ("Unknown status received", "收到未知状态"),
    ("Unknown error", "未知错误"),
    ("Form ref is empty", "表单引用为空"),
    ("No tasks found matching filters", "没有符合筛选条件的任务"),
    ("No projects found matching filters", "没有符合筛选条件的项目"),
    ("No jobs found matching filters", "没有符合筛选条件的作业"),
    ("No tasks found", "未找到任务"),
    ("No projects found", "未找到项目"),
    ("No jobs found", "未找到作业"),
    ("No models found", "未找到模型"),
    ("No data found", "未找到数据"),
    ("The field is required", "此字段为必填项"),
    ("This field is required", "此字段为必填项"),
    ("Field is required", "此字段为必填项"),

    # ─── 标注菜单 ─────────────────────────────────────────────
    ("Upload annotations", "上传标注"),
    ("Remove Annotations", "删除标注"),
    ("Remove annotations", "删除标注"),
    ("Run actions", "运行操作"),
    ("Open the task", "打开任务"),
    ("Finish the job", "完成作业"),
    ("Change job state", "更改作业状态"),
    ("Remove annotations from the current frame", "删除当前帧的标注"),
    ("Remove annotations from frames in range", "删除范围内帧的标注"),
    ("Remove all annotations", "删除所有标注"),
    ("Applicable only for annotations in range", "仅适用于范围内的标注"),

    # ─── 登录/注册 ────────────────────────────────────────────
    ("Forgot password?", "忘记密码？"),
    ("Create an account", "注册账号"),
    ("Email or username", "邮箱或用户名"),
    ("New user?", "新用户？"),
    ("Already have an account?", "已有账号？"),
    ("Have an account?", "已有账号？"),
    ("Already registered?", "已有账号？"),
    ("Back to login", "返回登录"),
    ("Create account", "创建账号"),
    ("Email confirmation", "邮箱确认"),
    ("Reset Password", "重置密码"),
    ("Reset password", "重置密码"),
    ("Set new password", "设置新密码"),
    ("Password reset", "密码重置"),
    ("Confirm new password", "确认新密码"),
    ("Confirm password", "确认密码"),
    ("Confirm Password", "确认密码"),
    ("Change password", "修改密码"),
    ("Change Password", "修改密码"),
    ("Current password", "当前密码"),
    ("New password", "新密码"),
    ("Password confirmation", "密码确认"),
    ("Sign in", "登录"),
    ("Sign In", "登录"),
    ("Sign up", "注册"),
    ("Sign Up", "注册"),
    ("Log in", "登录"),
    ("Log out", "退出登录"),
    ("Login", "登录"),
    ("Logout", "退出登录"),
    ("Register", "注册"),
    ("First name", "名"),
    ("Last name", "姓"),
    ("Full name", "全名"),
    ("Password", "密码"),
    ("Username", "用户名"),
    ("Email", "邮箱"),
    ("Phone number", "电话号码"),

    # ─── 导航栏 ───────────────────────────────────────────────
    ("Cloud Storages", "云存储"),
    ("Cloud Storage", "云存储"),
    ("Projects", "项目"),
    ("Project", "项目"),
    ("Tasks", "任务"),
    ("Task", "任务"),
    ("Jobs", "作业"),
    ("Job", "作业"),
    ("Models", "模型"),
    ("Model", "模型"),
    ("Analytics", "分析"),
    ("Requests", "请求"),
    ("Request", "请求"),
    ("Dashboard", "仪表盘"),
    ("Profile", "个人资料"),
    ("Settings", "设置"),
    ("About", "关于"),

    # ─── 组织 ─────────────────────────────────────────────────
    ("Personal workspace", "个人工作区"),
    ("Switch organization", "切换组织"),
    ("Create organization", "创建组织"),
    ("Create Organization", "创建组织"),
    ("Organization settings", "组织设置"),
    ("Organization name", "组织名称"),
    ("Organization slug", "组织标识"),
    ("Organization description", "组织描述"),
    ("Organization phone", "组织电话"),
    ("Organization location", "组织地址"),
    ("Organization", "组织"),
    ("Organizations", "组织"),
    ("Select an organization", "选择组织"),
    ("Members", "成员"),
    ("Member", "成员"),
    ("Invitations", "邀请"),
    ("Invitation", "邀请"),
    ("Invite members", "邀请成员"),
    ("Invite user", "邀请用户"),
    ("Remove member", "移除成员"),
    ("Leave organization", "退出组织"),
    ("Role", "角色"),
    ("Owner", "拥有者"),
    ("Admin", "管理员"),
    ("Maintainer", "维护者"),
    ("Supervisor", "监督员"),
    ("Worker", "工作人员"),
    ("Setup webhooks", "配置 Webhook"),

    # ─── 操作按钮 ─────────────────────────────────────────────
    ("Create new task", "新建任务"),
    ("Create new project", "新建项目"),
    ("Create a new task", "创建新任务"),
    ("Create a new project", "创建新项目"),
    ("Create a task", "创建任务"),
    ("Create a project", "创建项目"),
    ("Create multi tasks", "批量创建任务"),
    ("Create from backup", "从备份创建"),
    ("Create task", "创建任务"),
    ("Create project", "创建项目"),
    ("Create Job", "创建作业"),
    ("Create job", "创建作业"),
    ("Add files", "添加文件"),
    ("Add labels", "添加标签"),
    ("Add attribute", "添加属性"),
    ("Add sublabel", "添加子标签"),
    ("Add new label", "添加新标签"),
    ("Add points", "添加点"),
    ("Add", "添加"),
    ("Cancel", "取消"),
    ("Submit & Open", "提交并打开"),
    ("Submit & Continue", "提交并继续"),
    ("Submit", "提交"),
    ("Confirm", "确认"),
    ("Continue", "继续"),
    ("Save changes", "保存更改"),
    ("Save", "保存"),
    ("Update", "更新"),
    ("Delete selected", "删除所选"),
    ("Delete", "删除"),
    ("Remove label", "删除标签"),
    ("Remove task", "删除任务"),
    ("Remove", "移除"),
    ("Edit label", "编辑标签"),
    ("Edit", "编辑"),
    ("Close", "关闭"),
    ("Apply filters", "应用筛选"),
    ("Apply", "应用"),
    ("Reset", "重置"),
    ("Retry", "重试"),
    ("Refresh", "刷新"),
    ("Copy", "复制"),
    ("Paste", "粘贴"),
    ("Cut", "剪切"),
    ("Undo", "撤销"),
    ("Redo", "重做"),
    ("Search", "搜索"),
    ("Clear filters", "清除筛选"),
    ("Clear all", "清除全部"),
    ("Clear", "清除"),
    ("Filter", "筛选"),
    ("Sort", "排序"),
    ("Sort by", "排序方式"),
    ("Upload", "上传"),
    ("Download", "下载"),
    ("Export", "导出"),
    ("Import", "导入"),
    ("Back", "返回"),
    ("Next", "下一步"),
    ("Previous", "上一步"),
    ("Finish", "完成"),
    ("Done", "完成"),
    ("OK", "确定"),
    ("Yes", "是"),
    ("No", "否"),
    ("Open", "打开"),
    ("View analytics", "查看分析"),
    ("View", "查看"),
    ("Preview", "预览"),
    ("Expand all", "全部展开"),
    ("Collapse all", "全部折叠"),
    ("Expand", "展开"),
    ("Collapse", "收起"),
    ("Select all", "全选"),
    ("Select", "选择"),
    ("Deselect", "取消选择"),
    ("Move to project", "移动到项目"),
    ("Move task", "移动任务"),
    ("Move", "移动"),
    ("Rename", "重命名"),
    ("Duplicate", "复制"),
    ("Clone", "克隆"),
    ("Merge", "合并"),
    ("Split", "拆分"),
    ("Assign", "指派"),
    ("Unassign", "取消指派"),
    ("Share", "分享"),
    ("Lock all objects", "锁定所有对象"),
    ("Unlock all objects", "解锁所有对象"),
    ("Lock", "锁定"),
    ("Unlock", "解锁"),
    ("Hide all objects", "隐藏所有对象"),
    ("Show all objects", "显示所有对象"),
    ("Hide", "隐藏"),
    ("Show", "显示"),
    ("Freeze", "冻结"),
    ("Enable", "启用"),
    ("Disable", "禁用"),
    ("Activate", "激活"),
    ("Deactivate", "停用"),
    ("Archive", "归档"),
    ("Unarchive", "取消归档"),
    ("Restore", "恢复"),
    ("Use default settings", "使用默认设置"),
    ("Convert masks to polygons", "将掩码转换为多边形"),
    ("Copy labels from project", "从项目复制标签"),
    ("Keep existing labels", "保留现有标签"),
    ("Change project labels", "更改项目标签"),
    ("Load more", "加载更多"),
    ("Show more", "显示更多"),
    ("Show less", "显示更少"),

    # ─── 标注工具 ─────────────────────────────────────────────
    ("Draw new polygon", "绘制新多边形"),
    ("Draw new polyline", "绘制新折线"),
    ("Draw new rectangle", "绘制新矩形"),
    ("Draw new ellipse", "绘制新椭圆"),
    ("Draw new points", "绘制新点"),
    ("Draw new cuboid", "绘制新长方体"),
    ("Draw new mask", "绘制新掩码"),
    ("Draw new skeleton", "绘制新骨架"),
    ("Draw mask", "绘制掩码"),
    ("Draw mode", "绘制模式"),
    ("Edit mask", "编辑掩码"),
    ("Finish drawing", "完成绘制"),
    ("Continue drawing", "继续绘制"),
    ("Start drawing", "开始绘制"),
    ("Cancel drawing", "取消绘制"),
    ("Drawing in progress", "正在绘制"),
    ("Paste shape", "粘贴形状"),
    ("Automatic annotation", "自动标注"),
    ("Shape comparison", "形状比较"),
    ("Shape type", "形状类型"),
    ("Bounding box", "边界框"),
    ("Polygon", "多边形"),
    ("Polyline", "折线"),
    ("Points", "点"),
    ("Ellipse", "椭圆"),
    ("Cuboid", "长方体"),
    ("Skeleton", "骨架"),
    ("Mask", "掩码"),
    ("Rectangle", "矩形"),
    ("Track", "轨迹"),
    ("Region", "区域"),
    ("Instance", "实例"),

    # ─── 标注页面 ─────────────────────────────────────────────
    ("Color by instance", "按实例着色"),
    ("Color by group", "按组着色"),
    ("Color by label", "按标签着色"),
    ("Color by source", "按来源着色"),
    ("Selected opacity", "选中透明度"),
    ("Outline color", "轮廓颜色"),
    ("Shown labels", "显示标签"),
    ("Show all tags", "显示所有标签"),
    ("Show bitmasks", "显示位图掩码"),
    ("Show projections", "显示投影"),
    ("Auto borders", "自动边界"),
    ("Intelligent scissors", "智能剪刀"),
    ("Pixel snapping", "像素吸附"),
    ("Brush size", "笔刷大小"),
    ("Opacity", "透明度"),
    ("Appearance", "外观"),
    ("Fit image", "适应图像"),
    ("Fit objects", "适应对象"),
    ("Reset zoom", "重置缩放"),
    ("Zoom in", "放大"),
    ("Zoom out", "缩小"),
    ("Rotate clockwise", "顺时针旋转"),
    ("Rotate counter clockwise", "逆时针旋转"),
    ("Flip horizontally", "水平翻转"),
    ("Flip vertically", "垂直翻转"),
    ("First frame", "第一帧"),
    ("Last frame", "最后一帧"),
    ("Previous keyframe", "上一关键帧"),
    ("Next keyframe", "下一关键帧"),
    ("Previous empty frame", "上一空帧"),
    ("Next empty frame", "下一空帧"),
    ("Previous frame", "上一帧"),
    ("Next frame", "下一帧"),
    ("Go to frame", "跳转到帧"),
    ("Frame step", "帧步长"),
    ("Delay", "延迟"),
    ("Frame filters", "帧筛选"),
    ("Reset color settings", "重置颜色设置"),
    ("Image color settings", "图像颜色设置"),
    ("Brightness", "亮度"),
    ("Contrast", "对比度"),
    ("Saturation", "饱和度"),
    ("Propagate object", "传播对象"),
    ("Propagate", "传播"),
    ("Copy object", "复制对象"),
    ("Paste object", "粘贴对象"),
    ("Delete object", "删除对象"),
    ("Create instance", "创建实例"),
    ("Pin object", "固定对象"),
    ("Hide object", "隐藏对象"),
    ("Lock object", "锁定对象"),
    ("Object is hidden", "对象已隐藏"),
    ("Object is locked", "对象已锁定"),
    ("Object score", "对象评分"),
    ("Switch pinned property", "切换固定属性"),
    ("Switch occluded property", "切换遮挡属性"),
    ("Switch outside property", "切换超出范围属性"),
    ("Switch keyframe property", "切换关键帧属性"),
    ("Change start frame", "更改起始帧"),
    ("Change stop frame", "更改结束帧"),
    ("Keyframe", "关键帧"),
    ("Keyframes", "关键帧"),
    ("Not a keyframe", "非关键帧"),
    ("Occluded", "已遮挡"),
    ("Outside", "超出范围"),
    ("Pinned", "已固定"),
    ("Interpolated", "插值"),
    ("Points count", "点数"),
    ("Number of points", "点的数量"),
    ("Source", "来源"),
    ("Manual", "手动"),
    ("Automatic", "自动"),
    ("Auto", "自动"),
    ("Score", "评分"),
    ("Labels", "标签"),
    ("Label", "标签"),
    ("Attributes", "属性"),
    ("Attribute", "属性"),
    ("Value", "值"),
    ("Sublabels", "子标签"),
    ("Confirm action", "确认操作"),

    # ─── 任务/项目详情 ────────────────────────────────────────
    ("Task details", "任务详情"),
    ("Project details", "项目详情"),
    ("Job details", "作业详情"),
    ("Labels editor", "标签编辑器"),
    ("Labels content", "标签内容"),
    ("Raw labels", "原始标签"),
    ("Constructor", "构造器"),
    ("Continue configuration", "继续配置"),
    ("Open the task", "打开任务"),
    ("Open the job", "打开作业"),
    ("Open the project", "打开项目"),
    ("Open task", "打开任务"),
    ("Open job", "打开作业"),
    ("Open project", "打开项目"),
    ("Task is not assigned", "任务未指派"),
    ("Job is not assigned", "作业未指派"),
    ("Not assigned", "未指派"),
    ("Remove the task?", "删除任务？"),
    ("Delete the project?", "删除项目？"),
    ("Delete the job?", "删除作业？"),
    ("Move the task to the selected project", "将任务移动到所选项目"),
    ("Ground truth job", "真值作业"),
    ("Annotator", "标注员"),
    ("Assignees", "被指派人"),
    ("Reviewers", "审核人"),
    ("Assigned to me", "指派给我"),
    ("Not completed", "未完成"),
    ("Owned by me", "我所有"),
    ("No assignee", "无被指派人"),
    ("No reviewer", "无审核人"),
    ("Task name", "任务名称"),
    ("Project name", "项目名称"),
    ("Job name", "作业名称"),
    ("Project URL", "项目 URL"),
    ("Project Name", "项目名称"),
    ("Project ID", "项目 ID"),
    ("Task URL", "任务 URL"),
    ("Task ID", "任务 ID"),
    ("Job Type", "作业类型"),
    ("Parent ID", "父级 ID"),
    ("Replica", "副本"),
    ("Consensus replica", "共识副本"),
    ("Name template", "名称模板"),
    ("Custom name", "自定义名称"),
    ("Bug Tracker", "缺陷追踪器"),
    ("Bug tracker", "缺陷追踪器"),
    ("Source storage", "源存储"),
    ("Target storage", "目标存储"),
    ("Overlap size", "重叠大小"),
    ("Segment size", "分段大小"),
    ("Image quality", "图像质量"),
    ("Data chunk size", "数据块大小"),
    ("Start frame", "起始帧"),
    ("Stop frame", "结束帧"),
    ("Frame filter", "帧筛选"),
    ("Use zip chunks", "使用 zip 分块"),
    ("Use cache", "使用缓存"),
    ("Copy URL", "复制链接"),
    ("Issue tracker", "问题追踪器"),
    ("Open bug tracker", "打开缺陷追踪器"),
    ("Validation mode", "验证模式"),
    ("Frame selection method", "帧选择方法"),
    ("Frames per job segment", "每作业片段帧数"),
    ("Overlap frames", "重叠帧"),
    ("Random per job", "每作业随机"),
    ("Quantity per job", "每作业数量"),
    ("Quantity", "数量"),
    ("Honeypots", "蜜罐"),
    ("Annotator", "标注员"),
    ("Annotation", "标注"),
    ("Validation", "验证"),
    ("Acceptance", "接受"),
    ("Assignee", "被指派人"),
    ("Reviewer", "审核人"),
    ("Stage", "阶段"),
    ("State", "状态"),
    ("Status", "状态"),
    ("New", "新建"),
    ("In progress", "进行中"),
    ("Completed", "已完成"),
    ("Rejected", "已拒绝"),
    ("Archived", "已归档"),
    ("Active", "活跃"),
    ("Inactive", "非活跃"),
    ("Finished", "已完成"),
    ("Export task", "导出任务"),
    ("Export project", "导出项目"),
    ("Import task", "导入任务"),
    ("Import project", "导入项目"),
    ("Export dataset", "导出数据集"),
    ("Import dataset", "导入数据集"),
    ("Export annotations", "导出标注"),
    ("Import annotations", "导入标注"),
    ("Export backup", "导出备份"),
    ("Import backup", "导入备份"),
    ("Dump annotations", "导出标注"),
    ("Upload task annotations", "上传任务标注"),
    ("Upload project annotations", "上传项目标注"),
    ("Backup is not supported for", "不支持备份："),
    ("Select format", "选择格式"),
    ("Select dataset format", "选择数据集格式"),
    ("Actions", "操作"),
    ("Allocated frames", "已分配帧"),
    ("Frames", "帧"),
    ("Frame", "帧"),
    ("Size", "大小"),
    ("Mode", "模式"),
    ("Dimension", "维度"),
    ("Created", "创建时间"),
    ("Updated", "更新时间"),
    ("Created Date", "创建日期"),
    ("Updated Date", "更新日期"),
    ("Created date", "创建日期"),
    ("Updated date", "更新日期"),
    ("Last updated", "最后更新"),
    ("Created by", "创建者"),
    ("Updated by", "更新者"),
    ("Subset", "子集"),
    ("Version", "版本"),
    ("Format", "格式"),
    ("Page", "页面"),
    ("Items per page", "每页条目"),
    ("Total", "总计"),
    ("None", "无"),
    ("Any", "任意"),

    # ─── 筛选器 ───────────────────────────────────────────────
    ("Contains any", "包含任意"),
    ("Contains all", "包含全部"),
    ("Not contains", "不包含"),
    ("Equal", "等于"),
    ("Not equal", "不等于"),
    ("Greater than", "大于"),
    ("Less than", "小于"),
    ("Greater or equal", "大于等于"),
    ("Less or equal", "小于等于"),
    ("Between", "介于"),
    ("Add rule", "添加规则"),
    ("Add group", "添加组"),
    ("Remove rule", "删除规则"),
    ("No filters applied", "未应用筛选"),
    ("Recent filters", "最近的筛选"),
    ("Ascending", "升序"),
    ("Descending", "降序"),
    ("Group by", "分组方式"),
    ("2D", "2D"),
    ("3D", "3D"),

    # ─── 创建任务/数据 ────────────────────────────────────────
    ("Select files", "选择文件"),
    ("Select labels", "选择标签"),
    ("Select project", "选择项目"),
    ("Select task", "选择任务"),
    ("Select job", "选择作业"),
    ("Select label", "选择标签"),
    ("Select model", "选择模型"),
    ("Select storage", "选择存储"),
    ("Select cloud storage", "选择云存储"),
    ("Sorting method", "排序方法"),
    ("Use predefined subset", "使用预定义子集"),
    ("Source data", "源数据"),
    ("Share path", "共享路径"),
    ("Connected file share", "已连接的文件共享"),
    ("Allowed file types", "允许的文件类型"),
    ("Video frame rate", "视频帧率"),
    ("Natural sort", "自然排序"),
    ("Predefined", "预定义"),
    ("Random", "随机"),
    ("Honeypot", "蜜罐"),
    ("GT", "真值"),
    ("Local files", "本地文件"),
    ("Remote sources", "远程来源"),
    ("My computer", "我的电脑"),
    ("Remote URL", "远程 URL"),
    ("Predefined location", "预定义位置"),
    ("Select files", "选择文件"),
    ("Drop files here", "拖放文件到此处"),
    ("Browse", "浏览"),
    ("Basic configuration", "基础配置"),
    ("Advanced configuration", "高级配置"),
    ("Advanced", "高级"),
    ("Basic", "基础"),
    ("Optional", "可选"),
    ("Required", "必填"),

    # ─── 质量控制 ─────────────────────────────────────────────
    ("Quality control", "质量控制"),
    ("Quality reports", "质量报告"),
    ("Quality settings", "质量设置"),
    ("Quality summary", "质量摘要"),
    ("Consensus reports", "共识报告"),
    ("Consensus", "共识"),
    ("Ground truth", "真值"),
    ("Mean annotation quality", "平均标注质量"),
    ("Annotation quality", "标注质量"),
    ("Annotation accuracy", "标注准确率"),
    ("Annotation precision", "标注精确率"),
    ("Annotation recall", "标注召回率"),
    ("Annotation speed", "标注速度"),
    ("Mean accuracy", "平均准确率"),
    ("Validation frame count", "验证帧数"),
    ("Honeypot frames", "蜜罐帧"),
    ("Reviewed frames", "已审核帧"),
    ("Frames with conflicts", "有冲突的帧"),
    ("Valid annotations", "有效标注"),
    ("Invalid annotations", "无效标注"),
    ("Missing annotations", "缺失标注"),
    ("Extra annotations", "多余标注"),
    ("Matched annotations", "匹配的标注"),
    ("Unmatched annotations", "未匹配的标注"),
    ("Conflicting annotations", "有冲突的标注"),
    ("Dataset summary", "数据集摘要"),
    ("Annotation summary", "标注摘要"),
    ("Frame summary", "帧摘要"),
    ("Jobs summary", "作业摘要"),
    ("Total frames", "总帧数"),
    ("Annotated frames", "已标注帧"),
    ("Empty frames", "空帧"),
    ("Total annotations", "总标注数"),
    ("Total objects", "总对象数"),
    ("Objects per frame", "每帧对象数"),
    ("Number of annotations", "标注数量"),
    ("Working time", "工作时间"),
    ("Overlap threshold", "重叠阈值"),
    ("Low overlap threshold", "低重叠阈值"),
    ("Object count threshold", "对象数量阈值"),
    ("Panoptic comparison", "全景比较"),
    ("Shape comparison", "形状比较"),
    ("Conflicts", "冲突"),
    ("Conflict", "冲突"),
    ("Conflicts count", "冲突数量"),
    ("Issues count", "问题数量"),
    ("Warning count", "警告数量"),
    ("Error count", "错误数量"),
    ("Queued", "排队中"),
    ("In queue", "队列中"),
    ("Skipped", "已跳过"),
    ("Acceptable", "可接受"),
    ("Unacceptable", "不可接受"),
    ("No issues", "无问题"),
    ("Has issues", "有问题"),
    ("Performance", "性能"),

    # ─── 云存储 ───────────────────────────────────────────────
    ("Cloud storage name", "云存储名称"),
    ("Cloud storage", "云存储"),
    ("Provider type", "服务商类型"),
    ("Provider", "服务商"),
    ("Bucket name", "存储桶名称"),
    ("Account name", "账户名称"),
    ("Azure Blob Storage", "Azure Blob 存储"),
    ("Amazon S3", "Amazon S3"),
    ("Microsoft Azure", "Microsoft Azure"),
    ("Google Cloud Storage", "Google 云存储"),
    ("Anonymous access", "匿名访问"),
    ("Key id and secret key pair", "密钥 ID 和密钥对"),
    ("Temporary credentials", "临时凭证"),
    ("IAM role", "IAM 角色"),
    ("No credentials", "无凭证"),
    ("Public access", "公开访问"),
    ("Credentials file", "凭证文件"),
    ("Account name and token", "账户名称和令牌"),
    ("Credentials type", "凭证类型"),
    ("SAS token", "SAS 令牌"),
    ("SAS URL", "SAS URL"),
    ("Key ID", "密钥 ID"),
    ("Secret key", "密钥"),
    ("Key file", "密钥文件"),
    ("Session token", "会话令牌"),
    ("Endpoint URL", "端点 URL"),
    ("Region", "区域"),
    ("Prefix", "前缀"),
    ("Manifests", "清单文件"),
    ("Add manifest", "添加清单"),
    ("Test connection", "测试连接"),
    ("Connection is established", "连接已建立"),
    ("Connection failed", "连接失败"),
    ("Connected", "已连接"),
    ("Disconnected", "已断开"),
    ("Display name", "显示名称"),
    ("No description provided", "未提供描述"),
    ("Files in bucket:", "存储桶中的文件："),
    ("Manifests in bucket:", "存储桶中的清单："),

    # ─── 模型/AI ─────────────────────────────────────────────
    ("Interactive segmentation", "交互式分割"),
    ("Object detection", "目标检测"),
    ("Semantic segmentation", "语义分割"),
    ("Instance segmentation", "实例分割"),
    ("Pose estimation", "姿态估计"),
    ("Text detection", "文本检测"),
    ("Detector", "检测器"),
    ("Tracker", "跟踪器"),
    ("Interactor", "交互器"),
    ("Classifier", "分类器"),
    ("Serverless function", "无服务器函数"),
    ("Threshold", "阈值"),
    ("Max distance", "最大距离"),
    ("Run model", "运行模型"),
    ("Model runner", "模型运行器"),
    ("Active learning", "主动学习"),
    ("Run", "运行"),

    # ─── Webhook ──────────────────────────────────────────────
    ("Create webhook", "创建 Webhook"),
    ("Update webhook", "更新 Webhook"),
    ("Delete webhook", "删除 Webhook"),
    ("Webhook name", "Webhook 名称"),
    ("Webhooks", "Webhook"),
    ("Webhook", "Webhook"),
    ("Target URL", "目标 URL"),
    ("Content type", "内容类型"),
    ("Secret", "密钥"),
    ("Enable SSL verification", "启用 SSL 验证"),
    ("All events", "所有事件"),
    ("Selected events", "所选事件"),
    ("Events", "事件"),
    ("Payload", "载荷"),
    ("Deliveries", "推送记录"),
    ("Delivery", "推送记录"),
    ("Redelivery", "重新推送"),
    ("Response headers", "响应头"),
    ("Response body", "响应体"),
    ("Request headers", "请求头"),
    ("Request body", "请求体"),
    ("Response", "响应"),
    ("Success rate", "成功率"),
    ("Ping", "Ping"),

    # ─── 快捷键 ───────────────────────────────────────────────
    ("Keyboard shortcuts", "键盘快捷键"),
    ("Show shortcuts", "显示快捷键"),
    ("Show settings", "显示设置"),
    ("Shortcuts", "快捷键"),
    ("Shortcut", "快捷键"),

    # ─── 设置 ─────────────────────────────────────────────────
    ("Player settings", "播放器设置"),
    ("Workspace settings", "工作区设置"),
    ("Interface settings", "界面设置"),
    ("Controls settings", "控制设置"),
    ("Annotation filters", "标注筛选"),
    ("Display settings", "显示设置"),
    ("Show all interpolated tracks", "显示所有插值轨迹"),
    ("Show objects outside the frame", "显示帧外对象"),
    ("Auto save interval", "自动保存间隔"),
    ("Auto save", "自动保存"),
    ("Default number of points", "默认点数"),
    ("Automatically go to the next frame", "自动跳转到下一帧"),
    ("Automatically save when finish", "完成时自动保存"),
    ("Show predicted objects", "显示预测对象"),
    ("Smart polygon cropping", "智能多边形裁剪"),
    ("Keep primitive attributes", "保留原始属性"),
    ("Font size on image", "图像上字体大小"),
    ("Font size", "字体大小"),
    ("Smooth image", "图像平滑"),
    ("Grid size", "网格大小"),
    ("Grid color", "网格颜色"),
    ("Grid opacity", "网格透明度"),
    ("Grid", "网格"),
    ("Tag font size", "标签字体大小"),
    ("Text position", "文字位置"),
    ("Auto select polygon points", "自动选择多边形点"),
    ("Default approximation accuracy", "默认近似精度"),
    ("Resize objects", "调整对象大小"),
    ("Use shift clicking", "使用 Shift 点击"),
    ("Change label only for activated object", "仅为激活对象更改标签"),
    ("Language", "语言"),
    ("Theme", "主题"),
    ("Storage", "存储"),

    # ─── 标签编辑器 ──────────────────────────────────────────
    ("New label", "新标签"),
    ("Label name", "标签名称"),
    ("Label color", "标签颜色"),
    ("No attributes", "无属性"),
    ("Attribute name", "属性名称"),
    ("Attribute type", "属性类型"),
    ("Attribute values", "属性值"),
    ("Default value", "默认值"),
    ("Mutable", "可变"),
    ("Input type", "输入类型"),
    ("Checkbox", "复选框"),
    ("Radio", "单选框"),
    ("Number", "数字"),
    ("Text", "文本"),
    ("Add attribute value", "添加属性值"),

    # ─── 关于/导航链接 ────────────────────────────────────────
    ("Click to open repository", "点击打开仓库"),
    ("Click to open guide", "点击打开指南"),
    ("Admin page", "管理后台"),
    ("What's new?", "新功能"),
    ("MIT License", "MIT 许可证"),
    ("Find us on Discord", "在 Discord 上找到我们"),
    ("Server version:", "服务器版本："),
    ("UI version:", "UI 版本："),
    ("This is a paid feature", "这是付费功能"),
    ("Upgrade your plan", "升级您的套餐"),
    ("Contact us", "联系我们"),
    ("Reconnecting", "重新连接中"),

    # ─── 通用属性 ─────────────────────────────────────────────
    ("Name", "名称"),
    ("Color", "颜色"),
    ("Description", "描述"),
    ("Type", "类型"),
    ("Loading", "加载中"),
    ("Saving", "保存中"),
    ("Processing", "处理中"),
    ("Pending", "等待中"),
    ("Failed", "失败"),
    ("Success", "成功"),
    ("Warning", "警告"),
    ("Error", "错误"),
    ("Info", "信息"),
    ("Unknown", "未知"),
    ("Not found", "未找到"),
    ("No data", "暂无数据"),
    ("Location", "位置"),
    ("Default", "默认"),
    ("Custom", "自定义"),
    ("Interval", "间隔"),
    ("Duration", "时长"),
    ("Range", "范围"),
    ("From", "从"),
    ("Start", "开始"),
    ("End", "结束"),
    ("Width", "宽度"),
    ("Height", "高度"),
    ("Depth", "深度"),
    ("Count", "数量"),
    ("Index", "索引"),
    ("Order", "顺序"),
    ("Priority", "优先级"),
    ("Weight", "权重"),
    ("Percentage", "百分比"),
    ("Ratio", "比例"),
    ("Average", "平均"),
    ("Minimum", "最小值"),
    ("Maximum", "最大值"),
    ("Properties", "属性"),
    ("Overview", "概览"),
    ("Details", "详情"),
    ("Summary", "摘要"),
    ("Reports", "报告"),
    ("Report", "报告"),
    ("History", "历史记录"),
    ("Activity", "活动"),
    ("Notifications", "通知"),
    ("Notification", "通知"),
    ("Help", "帮助"),
    ("Guide", "指南"),
    ("Documentation", "文档"),
    ("Release notes", "发行说明"),
    ("Changelog", "更新日志"),
    ("License", "许可证"),
    ("Privacy", "隐私"),
    ("Terms", "条款"),
    ("Accept", "接受"),
    ("Decline", "拒绝"),
    ("Files", "文件"),
    ("File", "文件"),
    ("Folder", "文件夹"),
    ("Data", "数据"),
]

# ============================================================
# 辅助函数
# ============================================================

def should_skip_file(file_path: str) -> bool:
    skip_patterns = ['__tests__', '.test.', '.spec.', 'node_modules', '.d.ts']
    return any(p in file_path for p in skip_patterns)


def build_rules() -> list[tuple[str, str]]:
    """按长度降序排列，确保长字符串优先匹配"""
    sorted_trans = sorted(TRANSLATIONS, key=lambda x: len(x[0]), reverse=True)
    return [(re.escape(en), zh) for en, zh in sorted_trans]


def translate_content(content: str, rules: list[tuple[str, str]]) -> tuple[str, int]:
    total = 0
    for en_esc, zh in rules:
        # 1. 双引号字符串完整内容
        new, n = re.subn(r'"' + en_esc + r'"', f'"{zh}"', content)
        if n:
            content, total = new, total + n

        # 2. 单引号字符串完整内容
        new, n = re.subn(r"'" + en_esc + r"'", f"'{zh}'", content)
        if n:
            content, total = new, total + n

        # 3. JSX 内联文本：> Text < 或 > Text\n
        new, n = re.subn(
            r'(>[ \t]*)(' + en_esc + r')([ \t]*(?:<|[\r\n]))',
            r'\g<1>' + zh + r'\g<3>', content
        )
        if n:
            content, total = new, total + n

        # 4. JSX 独占行文本：<缩进>Text<行末>  （适用于 Button/Title 等）
        new, n = re.subn(
            r'^([ \t]*)(' + en_esc + r')([ \t]*)$',
            r'\g<1>' + zh + r'\g<3>', content,
            flags=re.MULTILINE
        )
        if n:
            content, total = new, total + n

    return content, total


def process_file(path: str, rules: list[tuple[str, str]], dry_run: bool = False) -> tuple[int, bool]:
    if should_skip_file(path):
        return 0, False
    try:
        original = open(path, encoding='utf-8').read()
    except Exception as e:
        print(f'  [跳过] {path}: {e}')
        return 0, False

    new_content, count = translate_content(original, rules)
    if count and not dry_run:
        open(path, 'w', encoding='utf-8').write(new_content)
    return count, count > 0


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--dry-run', action='store_true')
    parser.add_argument('--src', default='/Users/luochenyang/Downloads/cvat/cvat-ui/src')
    args = parser.parse_args()

    src = Path(args.src)
    if not src.exists():
        print(f'目录不存在: {src}')
        sys.exit(1)

    print(f'{"[预览] " if args.dry_run else ""}汉化 {src}')
    print(f'词条数：{len(TRANSLATIONS)}')
    print('=' * 60)

    rules = build_rules()
    files = [str(f) for f in sorted(src.rglob('*.tsx')) + sorted(src.rglob('*.ts'))
             if not should_skip_file(str(f))]

    changed_files, total_replacements = 0, 0
    for fp in files:
        count, changed = process_file(fp, rules, dry_run=args.dry_run)
        if changed:
            rel = os.path.relpath(fp, str(src))
            print(f'  [{count:4d}] {rel}')
            changed_files += 1
            total_replacements += count

    print('=' * 60)
    print(f'文件总数：{len(files)}，已修改：{changed_files}，替换次数：{total_replacements}')
    if args.dry_run:
        print('[预览模式：未写入文件]')


if __name__ == '__main__':
    main()
